# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bc8158a9c61f863c4c80126ef012ba3e2da889dcac7a316b1a6c08386144c710cff79743caf3614b83f25830389320f47cdfc2f35040f81c265b49b6a276644

test:
  secret_key_base: eb3b899b2fecef200cb840059ba3e2dbf6c6887ced1440a622aa5edfff6896660512ef5c3e40b06c4dbc19a00d4adbc8acf3afe16ff101ebe85da744901a6f5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
